server {
    listen 80;
    server_name localhost;

    # Serve static files from the dist directory
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # VERY IMPORTANT FOR REACT VITE SPAs:
        # If a file is not found (like /login), fallback to index.html 
        # so React Router can handle it client-side.
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
