"""Add SiemLog

Revision ID: 277480c6a15e
Revises: dd743047e8aa
Create Date: 2026-06-08 17:27:46.170339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277480c6a15e'
down_revision: Union[str, None] = 'dd743047e8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siem_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siem_logs_event_type'), 'siem_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_siem_logs_id'), 'siem_logs', ['id'], unique=False)
    op.create_index(op.f('ix_siem_logs_tenant_id'), 'siem_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_siem_logs_timestamp'), 'siem_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siem_logs_timestamp'), table_name='siem_logs')
    op.drop_index(op.f('ix_siem_logs_tenant_id'), table_name='siem_logs')
    op.drop_index(op.f('ix_siem_logs_id'), table_name='siem_logs')
    op.drop_index(op.f('ix_siem_logs_event_type'), table_name='siem_logs')
    op.drop_table('siem_logs')
    # ### end Alembic commands ###
