"""Add forensic metadata to evidence table

Revision ID: 90b724b432b6
Revises: 0004_add_is_deleted_to_evidence
Create Date: 2026-04-28 13:37:09.325356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b724b432b6'
down_revision: Union[str, None] = '0004_add_is_deleted_to_evidence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('evidence', sa.Column('source_vector', sa.String(length=100), nullable=True))
    op.add_column('evidence', sa.Column('forensic_data', sa.Text(), nullable=True))
    op.drop_index('scan_id', table_name='scans')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('scan_id', 'scans', ['scan_id'], unique=True)
    op.drop_column('evidence', 'forensic_data')
    op.drop_column('evidence', 'source_vector')
    op.drop_column('evidence', 'severity')
    op.drop_column('evidence', 'sha256')
    # ### end Alembic commands ###
