"""Add MonitorixAgent

Revision ID: dd743047e8aa
Revises: a8c1ac378b52
Create Date: 2026-06-08 17:22:54.874525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd743047e8aa'
down_revision: Union[str, None] = 'a8c1ac378b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitorix_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitorix_agents_id'), 'monitorix_agents', ['id'], unique=False)
    op.create_index(op.f('ix_monitorix_agents_tenant_id'), 'monitorix_agents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitorix_agents_tenant_id'), table_name='monitorix_agents')
    op.drop_index(op.f('ix_monitorix_agents_id'), table_name='monitorix_agents')
    op.drop_table('monitorix_agents')
    # ### end Alembic commands ###
