"""Add EvidenceVault

Revision ID: ff9ce235deab
Revises: 277480c6a15e
Create Date: 2026-06-08 17:29:26.735471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9ce235deab'
down_revision: Union[str, None] = '277480c6a15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_vault',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_vector', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('is_tampered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_vault_id'), 'evidence_vault', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_vault_sha256'), 'evidence_vault', ['sha256'], unique=False)
    op.create_index(op.f('ix_evidence_vault_tenant_id'), 'evidence_vault', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=512), nullable=True),
    sa.Column('sha256', sa.VARCHAR(length=64), nullable=True),
    sa.Column('evidence_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('source_vector', sa.VARCHAR(length=100), nullable=True),
    sa.Column('forensic_data', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.drop_index(op.f('ix_evidence_vault_tenant_id'), table_name='evidence_vault')
    op.drop_index(op.f('ix_evidence_vault_sha256'), table_name='evidence_vault')
    op.drop_index(op.f('ix_evidence_vault_id'), table_name='evidence_vault')
    op.drop_table('evidence_vault')
    # ### end Alembic commands ###
